package Acme::CPANLists::Import::PerlTricks::WhatsNewOnCPAN::201612;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perltricks.com/article/what-s-new-on-cpan---december-2016/] (retrieved on 2017-01-06). Visit the URL for the full contents.",entries=>[{module=>"Acme::Damn"},{module=>"App::RoboBot"},{module=>"App::TestOnTap"},{module=>"App::UnANSI"},{module=>"B::CompilerPhase::Hook"},{module=>"BEGIN::Lift"},{module=>"Bb::Collaborate::Ultra"},{module=>"Beam::Runner"},{module=>"Catalyst::Plugin::Perlinfo"},{module=>"Chart::Bokeh"},{module=>"Crypt::Perl"},{module=>"Dancer2::Plugin::ParamTypes"},{module=>"Data::Layout::BuddySystem"},{module=>"Data::ULID"},{module=>"Game::Asset"},{module=>"HTML::Notebook"},{module=>"JIRA::REST::Class"},{module=>"JSON::RPC2::TwoWay"},{module=>"Lingua::Postcodes"},{module=>"MarpaX::Languages::Dash"},{module=>"MojoX::LineStream"},{module=>"Mojolicious::Plugin::Subprocess"},{module=>"Mongol"},{module=>"Monitor::MetricsAPI"},{module=>"Moonshine::Element"},{module=>"MooseX::EventEmitter"},{module=>"Net::Azure::CognitiveServices::Face"},{module=>"Pod::Confluence"},{module=>"Redis::RateLimit"},{module=>"Stepford::Grapher"},{module=>"Sub::Versions"},{module=>"Text::Diff::Unified::XS"},{module=>"UMLS::Association"},{module=>"UNIVERSAL::Object"},{module=>"WWW::Wikipedia::LangTitles"}],summary=>"Modules mentioned in PerlTricks.com's What's New on CPAN article, edition Dec 2016"});

1;
# ABSTRACT: Modules mentioned in PerlTricks.com's What's New on CPAN article, edition Dec 2016

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perltricks.com/article/what-s-new-on-cpan---december-2016/> (retrieved on 2017-01-06). Visit the URL for the full contents.

